# Generated by Django 3.0.3 on 2020-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('year', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
    ]
