# Generated by Django 3.0.3 on 2020-03-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carr',
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('model',)},
        ),
    ]
